### ISSUE TITLE
xtrace-20190808  AsyncClient.searchTraces  darabonba.core.exception.TeaException: darabonba.core.exception.TeaException: key == null

### ISSUE THREAD

**Issue by 1194117884** [aliyun/alibabacloud-java-sdk#22]
### Exception:
`Caused by: darabonba.core.exception.TeaException: darabonba.core.exception.TeaException: key == null
	at com.aliyun.sdk.gateway.pop.interceptor.output.FinalizedOutputInterceptor.modifyOutput(FinalizedOutputInterceptor.java:33)
	at darabonba.core.interceptor.InterceptorChain.modifyOutput(InterceptorChain.java:96)
	at darabonba.core.TeaAsyncHandler$RetryableExecutor.lambda$attemptExecute$0(TeaAsyncHandler.java:289)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.aliyun.httpcomponent.httpclient.ApacheAsyncHttpClient$1.completed(ApacheAsyncHttpClient.java:133)
	at com.aliyun.httpcomponent.httpclient.ApacheAsyncHttpClient$1.completed(ApacheAsyncHttpClient.java:130)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1$3$1.completed(InternalAbstractHttpAsyncClient.java:298)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer$2.completed(AbstractAsyncResponseConsumer.java:108)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:84)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:81)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:149)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:233)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:280)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:333)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:39)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:550)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$400(SSLIOSession.java:72)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:172)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:131)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:85)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.lang.Thread.run(Thread.java:750)`

### Method:
AsyncClient.java

`CompletableFuture<SearchTracesResponse> searchTraces(SearchTracesRequest request);`

### Screenshot
![image](https://user-images.githubusercontent.com/12094568/236613153-2e129e01-0a39-433d-a56d-90522c7b72dd.png)

### Maybe 
The HTTP request has been completed. 

When constructing the 'teaResponse.deserializedBody,' using the method 'ParseUtil.readAsJSON()', and it will return a responseBody who's class is 'com.google.gson.internal.LinkedTreeMap'. 

If you call 'put(null, null)', it will throw a 'NullPointerException' instead of an 'UnsupportedOperationException'. 

**In additional to 'UnmodifiableMap', there is also 'LinkedTreeMap'**

**Comment by TsinghuaDream** [comment]
升级下这个包再看看呢
    <dependency>
      <groupId>com.aliyun</groupId>
      <artifactId>aliyun-gateway-pop</artifactId>
      <version>0.2.9-beta</version>
    </dependency>
